apiVersion: apps/v1
kind: Deployment
metadata:
  name: ls-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ls-backend
  template:
    metadata:
      labels:
        app: ls-backend
    spec:
      containers:
      - name: ls-backend
        image: hariramprasanth/live-stream-backend:8017935198
        ports:
        - containerPort: 8080
        env:
          - name: VIDEOS_DIRECTORY
            value: /videos

---

kind: Service
apiVersion: v1
metadata:
  name:  ls-backend
spec:
  selector:
    app: ls-backend
  type: ClusterIP 
  ports:
  - name: ls-backend
    port:  80
    targetPort:  8080

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: ls-backend-lb
#   annotations:
#     service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-south-1:160071257600:certificate/e7324c70-1689-407b-9ae0-64ad6d92627e
#     service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
# spec:
#   selector:
#     app: ls-backend
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 8080
#       name: http-port
#     - protocol: TCP
#       port: 443
#       targetPort: 8080
#       name: https-port
#   type: LoadBalancer
